# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'probando.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1350, 700)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.frame_cliente = QtGui.QFrame(self.centralWidget)
        self.frame_cliente.setGeometry(QtCore.QRect(20, 50, 280, 581))
        self.frame_cliente.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_cliente.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_cliente.setObjectName(_fromUtf8("frame_cliente"))
        self.TE_Nombre = QtGui.QPlainTextEdit(self.frame_cliente)
        self.TE_Nombre.setGeometry(QtCore.QRect(70, 20, 201, 31))
        self.TE_Nombre.setTabChangesFocus(True)
        self.TE_Nombre.setObjectName(_fromUtf8("TE_Nombre"))
        self.label = QtGui.QLabel(self.frame_cliente)
        self.label.setGeometry(QtCore.QRect(10, 30, 60, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_5 = QtGui.QLabel(self.frame_cliente)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 60, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.TE_Telefono = QtGui.QPlainTextEdit(self.frame_cliente)
        self.TE_Telefono.setGeometry(QtCore.QRect(70, 60, 201, 31))
        self.TE_Telefono.setTabChangesFocus(True)
        self.TE_Telefono.setObjectName(_fromUtf8("TE_Telefono"))
        self.label_6 = QtGui.QLabel(self.frame_cliente)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 60, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.TE_Direccion = QtGui.QPlainTextEdit(self.frame_cliente)
        self.TE_Direccion.setGeometry(QtCore.QRect(70, 100, 201, 51))
        self.TE_Direccion.setTabChangesFocus(True)
        self.TE_Direccion.setObjectName(_fromUtf8("TE_Direccion"))
        self.TE_Comentario = QtGui.QPlainTextEdit(self.frame_cliente)
        self.TE_Comentario.setGeometry(QtCore.QRect(70, 200, 201, 51))
        self.TE_Comentario.setTabChangesFocus(True)
        self.TE_Comentario.setObjectName(_fromUtf8("TE_Comentario"))
        self.label_7 = QtGui.QLabel(self.frame_cliente)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 60, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.PB_Imprimir = QtGui.QPushButton(self.frame_cliente)
        self.PB_Imprimir.setGeometry(QtCore.QRect(10, 470, 131, 41))
        self.PB_Imprimir.setObjectName(_fromUtf8("PB_Imprimir"))
        self.TE_Uber = QtGui.QPlainTextEdit(self.frame_cliente)
        self.TE_Uber.setGeometry(QtCore.QRect(70, 160, 201, 31))
        self.TE_Uber.setTabChangesFocus(True)
        self.TE_Uber.setObjectName(_fromUtf8("TE_Uber"))
        self.label_9 = QtGui.QLabel(self.frame_cliente)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 60, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.PB_Limpiar = QtGui.QPushButton(self.frame_cliente)
        self.PB_Limpiar.setGeometry(QtCore.QRect(10, 540, 131, 41))
        self.PB_Limpiar.setObjectName(_fromUtf8("PB_Limpiar"))
        self.TE_Efectivo = QtGui.QPlainTextEdit(self.frame_cliente)
        self.TE_Efectivo.setGeometry(QtCore.QRect(140, 300, 121, 31))
        self.TE_Efectivo.setTabChangesFocus(True)
        self.TE_Efectivo.setObjectName(_fromUtf8("TE_Efectivo"))
        self.CB_Imprimir_Comandas = QtGui.QCheckBox(self.frame_cliente)
        self.CB_Imprimir_Comandas.setGeometry(QtCore.QRect(20, 430, 191, 20))
        self.CB_Imprimir_Comandas.setChecked(True)
        self.CB_Imprimir_Comandas.setObjectName(_fromUtf8("CB_Imprimir_Comandas"))
        self.PB_buscar = QtGui.QPushButton(self.frame_cliente)
        self.PB_buscar.setGeometry(QtCore.QRect(150, 540, 131, 41))
        self.PB_buscar.setObjectName(_fromUtf8("PB_buscar"))
        self.PB_ultimo_cliente = QtGui.QPushButton(self.frame_cliente)
        self.PB_ultimo_cliente.setGeometry(QtCore.QRect(150, 470, 131, 41))
        self.PB_ultimo_cliente.setObjectName(_fromUtf8("PB_ultimo_cliente"))
        self.CB_Descuento = QtGui.QCheckBox(self.frame_cliente)
        self.CB_Descuento.setGeometry(QtCore.QRect(40, 350, 91, 20))
        self.CB_Descuento.setChecked(False)
        self.CB_Descuento.setObjectName(_fromUtf8("CB_Descuento"))
        self.label_8 = QtGui.QLabel(self.frame_cliente)
        self.label_8.setGeometry(QtCore.QRect(60, 310, 60, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.combo_box_forma_pago = QtGui.QComboBox(self.frame_cliente)
        self.combo_box_forma_pago.setGeometry(QtCore.QRect(10, 260, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.combo_box_forma_pago.setFont(font)
        self.combo_box_forma_pago.setObjectName(_fromUtf8("combo_box_forma_pago"))
        self.combo_box_descuento = QtGui.QComboBox(self.frame_cliente)
        self.combo_box_descuento.setGeometry(QtCore.QRect(140, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.combo_box_descuento.setFont(font)
        self.combo_box_descuento.setObjectName(_fromUtf8("combo_box_descuento"))
        self.combo_box_promo = QtGui.QComboBox(self.frame_cliente)
        self.combo_box_promo.setGeometry(QtCore.QRect(140, 380, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.combo_box_promo.setFont(font)
        self.combo_box_promo.setObjectName(_fromUtf8("combo_box_promo"))
        self.CB_Promo = QtGui.QCheckBox(self.frame_cliente)
        self.CB_Promo.setGeometry(QtCore.QRect(40, 390, 91, 20))
        self.CB_Promo.setChecked(False)
        self.CB_Promo.setObjectName(_fromUtf8("CB_Promo"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(310, 10, 300, 261))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.PB_Nuevo = QtGui.QPushButton(self.frame)
        self.PB_Nuevo.setEnabled(True)
        self.PB_Nuevo.setGeometry(QtCore.QRect(0, 10, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.PB_Nuevo.setFont(font)
        self.PB_Nuevo.setCheckable(False)
        self.PB_Nuevo.setAutoDefault(False)
        self.PB_Nuevo.setDefault(False)
        self.PB_Nuevo.setFlat(False)
        self.PB_Nuevo.setObjectName(_fromUtf8("PB_Nuevo"))
        self.PB_Nuevo_2 = QtGui.QPushButton(self.frame)
        self.PB_Nuevo_2.setGeometry(QtCore.QRect(150, 10, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Nuevo_2.setFont(font)
        self.PB_Nuevo_2.setObjectName(_fromUtf8("PB_Nuevo_2"))
        self.PB_Nuevo_3 = QtGui.QPushButton(self.frame)
        self.PB_Nuevo_3.setGeometry(QtCore.QRect(0, 60, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Nuevo_3.setFont(font)
        self.PB_Nuevo_3.setObjectName(_fromUtf8("PB_Nuevo_3"))
        self.PB_Nuevo_4 = QtGui.QPushButton(self.frame)
        self.PB_Nuevo_4.setGeometry(QtCore.QRect(150, 60, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Nuevo_4.setFont(font)
        self.PB_Nuevo_4.setObjectName(_fromUtf8("PB_Nuevo_4"))
        self.PB_Nuevo_5 = QtGui.QPushButton(self.frame)
        self.PB_Nuevo_5.setGeometry(QtCore.QRect(0, 110, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Nuevo_5.setFont(font)
        self.PB_Nuevo_5.setObjectName(_fromUtf8("PB_Nuevo_5"))
        self.PB_Nuevo_6 = QtGui.QPushButton(self.frame)
        self.PB_Nuevo_6.setGeometry(QtCore.QRect(150, 110, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Nuevo_6.setFont(font)
        self.PB_Nuevo_6.setObjectName(_fromUtf8("PB_Nuevo_6"))
        self.PB_Nuevo_7 = QtGui.QPushButton(self.frame)
        self.PB_Nuevo_7.setGeometry(QtCore.QRect(0, 160, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Nuevo_7.setFont(font)
        self.PB_Nuevo_7.setObjectName(_fromUtf8("PB_Nuevo_7"))
        self.PB_Nuevo_8 = QtGui.QPushButton(self.frame)
        self.PB_Nuevo_8.setGeometry(QtCore.QRect(150, 160, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Nuevo_8.setFont(font)
        self.PB_Nuevo_8.setObjectName(_fromUtf8("PB_Nuevo_8"))
        self.PB_Nuevo_9 = QtGui.QPushButton(self.frame)
        self.PB_Nuevo_9.setGeometry(QtCore.QRect(0, 210, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Nuevo_9.setFont(font)
        self.PB_Nuevo_9.setObjectName(_fromUtf8("PB_Nuevo_9"))
        self.PB_Nuevo_10 = QtGui.QPushButton(self.frame)
        self.PB_Nuevo_10.setGeometry(QtCore.QRect(150, 210, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Nuevo_10.setFont(font)
        self.PB_Nuevo_10.setObjectName(_fromUtf8("PB_Nuevo_10"))
        self.frame_2 = QtGui.QFrame(self.centralWidget)
        self.frame_2.setGeometry(QtCore.QRect(310, 280, 300, 351))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.PB_Item = QtGui.QPushButton(self.frame_2)
        self.PB_Item.setGeometry(QtCore.QRect(0, 0, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item.setFont(font)
        self.PB_Item.setObjectName(_fromUtf8("PB_Item"))
        self.PB_Item_2 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_2.setGeometry(QtCore.QRect(150, 0, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_2.setFont(font)
        self.PB_Item_2.setObjectName(_fromUtf8("PB_Item_2"))
        self.PB_Item_3 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_3.setGeometry(QtCore.QRect(0, 50, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_3.setFont(font)
        self.PB_Item_3.setObjectName(_fromUtf8("PB_Item_3"))
        self.PB_Item_4 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_4.setGeometry(QtCore.QRect(150, 50, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_4.setFont(font)
        self.PB_Item_4.setObjectName(_fromUtf8("PB_Item_4"))
        self.PB_Item_5 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_5.setGeometry(QtCore.QRect(0, 100, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_5.setFont(font)
        self.PB_Item_5.setObjectName(_fromUtf8("PB_Item_5"))
        self.PB_Item_6 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_6.setGeometry(QtCore.QRect(150, 100, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_6.setFont(font)
        self.PB_Item_6.setObjectName(_fromUtf8("PB_Item_6"))
        self.PB_Item_7 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_7.setGeometry(QtCore.QRect(0, 150, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_7.setFont(font)
        self.PB_Item_7.setObjectName(_fromUtf8("PB_Item_7"))
        self.PB_Item_8 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_8.setGeometry(QtCore.QRect(150, 150, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_8.setFont(font)
        self.PB_Item_8.setObjectName(_fromUtf8("PB_Item_8"))
        self.PB_Item_9 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_9.setGeometry(QtCore.QRect(0, 200, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_9.setFont(font)
        self.PB_Item_9.setObjectName(_fromUtf8("PB_Item_9"))
        self.PB_Item_10 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_10.setGeometry(QtCore.QRect(150, 200, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_10.setFont(font)
        self.PB_Item_10.setObjectName(_fromUtf8("PB_Item_10"))
        self.PB_Item_11 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_11.setGeometry(QtCore.QRect(0, 250, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_11.setFont(font)
        self.PB_Item_11.setObjectName(_fromUtf8("PB_Item_11"))
        self.PB_Item_12 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_12.setGeometry(QtCore.QRect(150, 250, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_12.setFont(font)
        self.PB_Item_12.setObjectName(_fromUtf8("PB_Item_12"))
        self.PB_Item_13 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_13.setGeometry(QtCore.QRect(0, 300, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_13.setFont(font)
        self.PB_Item_13.setObjectName(_fromUtf8("PB_Item_13"))
        self.PB_Item_14 = QtGui.QPushButton(self.frame_2)
        self.PB_Item_14.setGeometry(QtCore.QRect(150, 300, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Item_14.setFont(font)
        self.PB_Item_14.setObjectName(_fromUtf8("PB_Item_14"))
        self.frame_3 = QtGui.QFrame(self.centralWidget)
        self.frame_3.setGeometry(QtCore.QRect(620, 10, 240, 621))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.PB_Adc = QtGui.QPushButton(self.frame_3)
        self.PB_Adc.setGeometry(QtCore.QRect(0, 0, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc.setFont(font)
        self.PB_Adc.setObjectName(_fromUtf8("PB_Adc"))
        self.PB_Adc_2 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_2.setGeometry(QtCore.QRect(0, 30, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_2.setFont(font)
        self.PB_Adc_2.setObjectName(_fromUtf8("PB_Adc_2"))
        self.PB_Adc_3 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_3.setGeometry(QtCore.QRect(0, 60, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_3.setFont(font)
        self.PB_Adc_3.setObjectName(_fromUtf8("PB_Adc_3"))
        self.PB_Adc_4 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_4.setGeometry(QtCore.QRect(0, 90, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_4.setFont(font)
        self.PB_Adc_4.setObjectName(_fromUtf8("PB_Adc_4"))
        self.PB_Adc_5 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_5.setGeometry(QtCore.QRect(0, 120, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_5.setFont(font)
        self.PB_Adc_5.setObjectName(_fromUtf8("PB_Adc_5"))
        self.PB_Adc_6 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_6.setGeometry(QtCore.QRect(0, 150, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_6.setFont(font)
        self.PB_Adc_6.setObjectName(_fromUtf8("PB_Adc_6"))
        self.PB_Adc_7 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_7.setGeometry(QtCore.QRect(0, 180, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_7.setFont(font)
        self.PB_Adc_7.setObjectName(_fromUtf8("PB_Adc_7"))
        self.PB_Adc_8 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_8.setGeometry(QtCore.QRect(0, 210, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_8.setFont(font)
        self.PB_Adc_8.setObjectName(_fromUtf8("PB_Adc_8"))
        self.PB_Adc_9 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_9.setGeometry(QtCore.QRect(0, 240, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_9.setFont(font)
        self.PB_Adc_9.setObjectName(_fromUtf8("PB_Adc_9"))
        self.PB_Adc_10 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_10.setGeometry(QtCore.QRect(0, 270, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_10.setFont(font)
        self.PB_Adc_10.setObjectName(_fromUtf8("PB_Adc_10"))
        self.PB_Adc_11 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_11.setGeometry(QtCore.QRect(0, 300, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_11.setFont(font)
        self.PB_Adc_11.setObjectName(_fromUtf8("PB_Adc_11"))
        self.PB_Adc_12 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_12.setGeometry(QtCore.QRect(0, 330, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_12.setFont(font)
        self.PB_Adc_12.setObjectName(_fromUtf8("PB_Adc_12"))
        self.PB_Adc_13 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_13.setGeometry(QtCore.QRect(0, 360, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_13.setFont(font)
        self.PB_Adc_13.setObjectName(_fromUtf8("PB_Adc_13"))
        self.PB_Adc_14 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_14.setGeometry(QtCore.QRect(0, 390, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_14.setFont(font)
        self.PB_Adc_14.setObjectName(_fromUtf8("PB_Adc_14"))
        self.PB_Adc_15 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_15.setGeometry(QtCore.QRect(0, 420, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_15.setFont(font)
        self.PB_Adc_15.setObjectName(_fromUtf8("PB_Adc_15"))
        self.PB_Adc_16 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_16.setGeometry(QtCore.QRect(0, 450, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_16.setFont(font)
        self.PB_Adc_16.setObjectName(_fromUtf8("PB_Adc_16"))
        self.PB_Adc_17 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_17.setGeometry(QtCore.QRect(0, 480, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_17.setFont(font)
        self.PB_Adc_17.setObjectName(_fromUtf8("PB_Adc_17"))
        self.PB_Adc_18 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_18.setGeometry(QtCore.QRect(0, 510, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_18.setFont(font)
        self.PB_Adc_18.setObjectName(_fromUtf8("PB_Adc_18"))
        self.PB_Adc_19 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_19.setGeometry(QtCore.QRect(0, 540, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_19.setFont(font)
        self.PB_Adc_19.setObjectName(_fromUtf8("PB_Adc_19"))
        self.PB_Adc_20 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_20.setGeometry(QtCore.QRect(0, 570, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_20.setFont(font)
        self.PB_Adc_20.setObjectName(_fromUtf8("PB_Adc_20"))
        self.PB_Adc_21 = QtGui.QPushButton(self.frame_3)
        self.PB_Adc_21.setGeometry(QtCore.QRect(0, 600, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Adc_21.setFont(font)
        self.PB_Adc_21.setObjectName(_fromUtf8("PB_Adc_21"))
        self.frame_4 = QtGui.QFrame(self.centralWidget)
        self.frame_4.setGeometry(QtCore.QRect(870, 0, 111, 621))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.cb_ingredientes = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes.setGeometry(QtCore.QRect(10, 20, 150, 50))
        self.cb_ingredientes.setObjectName(_fromUtf8("cb_ingredientes"))
        self.cb_ingredientes_2 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_2.setGeometry(QtCore.QRect(10, 70, 150, 50))
        self.cb_ingredientes_2.setObjectName(_fromUtf8("cb_ingredientes_2"))
        self.cb_ingredientes_3 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_3.setGeometry(QtCore.QRect(10, 120, 150, 50))
        self.cb_ingredientes_3.setObjectName(_fromUtf8("cb_ingredientes_3"))
        self.cb_ingredientes_4 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_4.setGeometry(QtCore.QRect(10, 170, 150, 50))
        self.cb_ingredientes_4.setObjectName(_fromUtf8("cb_ingredientes_4"))
        self.cb_ingredientes_5 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_5.setGeometry(QtCore.QRect(10, 220, 150, 50))
        self.cb_ingredientes_5.setObjectName(_fromUtf8("cb_ingredientes_5"))
        self.cb_ingredientes_6 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_6.setGeometry(QtCore.QRect(10, 270, 150, 50))
        self.cb_ingredientes_6.setObjectName(_fromUtf8("cb_ingredientes_6"))
        self.cb_ingredientes_7 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_7.setGeometry(QtCore.QRect(10, 320, 150, 50))
        self.cb_ingredientes_7.setObjectName(_fromUtf8("cb_ingredientes_7"))
        self.cb_ingredientes_8 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_8.setGeometry(QtCore.QRect(10, 370, 150, 50))
        self.cb_ingredientes_8.setObjectName(_fromUtf8("cb_ingredientes_8"))
        self.cb_ingredientes_9 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_9.setGeometry(QtCore.QRect(10, 420, 150, 50))
        self.cb_ingredientes_9.setObjectName(_fromUtf8("cb_ingredientes_9"))
        self.cb_ingredientes_10 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_10.setGeometry(QtCore.QRect(10, 470, 150, 50))
        self.cb_ingredientes_10.setObjectName(_fromUtf8("cb_ingredientes_10"))
        self.cb_ingredientes_11 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_11.setGeometry(QtCore.QRect(10, 520, 150, 50))
        self.cb_ingredientes_11.setObjectName(_fromUtf8("cb_ingredientes_11"))
        self.cb_ingredientes_12 = QtGui.QCheckBox(self.frame_4)
        self.cb_ingredientes_12.setGeometry(QtCore.QRect(10, 570, 150, 50))
        self.cb_ingredientes_12.setObjectName(_fromUtf8("cb_ingredientes_12"))
        self.frame_5 = QtGui.QFrame(self.centralWidget)
        self.frame_5.setGeometry(QtCore.QRect(990, 10, 350, 621))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.listWidget_ticket = QtGui.QListWidget(self.frame_5)
        self.listWidget_ticket.setGeometry(QtCore.QRect(-1, 0, 351, 431))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.listWidget_ticket.setFont(font)
        self.listWidget_ticket.setObjectName(_fromUtf8("listWidget_ticket"))
        self.label_2 = QtGui.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(10, 550, 60, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(10, 440, 60, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(130, 440, 60, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_10 = QtGui.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(240, 440, 60, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.TE_Total = QtGui.QLabel(self.frame_5)
        self.TE_Total.setGeometry(QtCore.QRect(10, 570, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.TE_Total.setFont(font)
        self.TE_Total.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TE_Total.setFrameShape(QtGui.QFrame.Box)
        self.TE_Total.setFrameShadow(QtGui.QFrame.Raised)
        self.TE_Total.setLineWidth(2)
        self.TE_Total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TE_Total.setObjectName(_fromUtf8("TE_Total"))
        self.lb_forma_de_pago = QtGui.QLabel(self.frame_5)
        self.lb_forma_de_pago.setGeometry(QtCore.QRect(120, 530, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.lb_forma_de_pago.setFont(font)
        self.lb_forma_de_pago.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_forma_de_pago.setObjectName(_fromUtf8("lb_forma_de_pago"))
        self.lb_forma_de_entrega = QtGui.QLabel(self.frame_5)
        self.lb_forma_de_entrega.setGeometry(QtCore.QRect(120, 500, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.lb_forma_de_entrega.setFont(font)
        self.lb_forma_de_entrega.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_forma_de_entrega.setObjectName(_fromUtf8("lb_forma_de_entrega"))
        self.TE_Bowls = QtGui.QLabel(self.frame_5)
        self.TE_Bowls.setGeometry(QtCore.QRect(10, 460, 100, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.TE_Bowls.setFont(font)
        self.TE_Bowls.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TE_Bowls.setFrameShape(QtGui.QFrame.WinPanel)
        self.TE_Bowls.setFrameShadow(QtGui.QFrame.Raised)
        self.TE_Bowls.setAlignment(QtCore.Qt.AlignCenter)
        self.TE_Bowls.setObjectName(_fromUtf8("TE_Bowls"))
        self.TE_Bebidas = QtGui.QLabel(self.frame_5)
        self.TE_Bebidas.setGeometry(QtCore.QRect(130, 460, 100, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.TE_Bebidas.setFont(font)
        self.TE_Bebidas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TE_Bebidas.setFrameShape(QtGui.QFrame.WinPanel)
        self.TE_Bebidas.setFrameShadow(QtGui.QFrame.Raised)
        self.TE_Bebidas.setAlignment(QtCore.Qt.AlignCenter)
        self.TE_Bebidas.setObjectName(_fromUtf8("TE_Bebidas"))
        self.TE_Postres = QtGui.QLabel(self.frame_5)
        self.TE_Postres.setGeometry(QtCore.QRect(240, 460, 100, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.TE_Postres.setFont(font)
        self.TE_Postres.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TE_Postres.setFrameShape(QtGui.QFrame.WinPanel)
        self.TE_Postres.setFrameShadow(QtGui.QFrame.Raised)
        self.TE_Postres.setAlignment(QtCore.Qt.AlignCenter)
        self.TE_Postres.setObjectName(_fromUtf8("TE_Postres"))
        self.combo_box_entrega = QtGui.QComboBox(self.centralWidget)
        self.combo_box_entrega.setGeometry(QtCore.QRect(20, 10, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.combo_box_entrega.setFont(font)
        self.combo_box_entrega.setObjectName(_fromUtf8("combo_box_entrega"))
        self.listWidget_comanda = QtGui.QListWidget(self.centralWidget)
        self.listWidget_comanda.setEnabled(True)
        self.listWidget_comanda.setGeometry(QtCore.QRect(1220, 640, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.listWidget_comanda.setFont(font)
        self.listWidget_comanda.setStatusTip(_fromUtf8(""))
        self.listWidget_comanda.setObjectName(_fromUtf8("listWidget_comanda"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1350, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuCAJA = QtGui.QMenu(self.menuBar)
        self.menuCAJA.setObjectName(_fromUtf8("menuCAJA"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbrir_Forumulario = QtGui.QAction(MainWindow)
        self.actionAbrir_Forumulario.setObjectName(_fromUtf8("actionAbrir_Forumulario"))
        self.menuCAJA.addAction(self.actionAbrir_Forumulario)
        self.menuBar.addAction(self.menuCAJA.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.combo_box_entrega, self.TE_Nombre)
        MainWindow.setTabOrder(self.TE_Nombre, self.TE_Telefono)
        MainWindow.setTabOrder(self.TE_Telefono, self.TE_Direccion)
        MainWindow.setTabOrder(self.TE_Direccion, self.TE_Uber)
        MainWindow.setTabOrder(self.TE_Uber, self.TE_Comentario)
        MainWindow.setTabOrder(self.TE_Comentario, self.combo_box_forma_pago)
        MainWindow.setTabOrder(self.combo_box_forma_pago, self.TE_Efectivo)
        MainWindow.setTabOrder(self.TE_Efectivo, self.CB_Descuento)
        MainWindow.setTabOrder(self.CB_Descuento, self.combo_box_descuento)
        MainWindow.setTabOrder(self.combo_box_descuento, self.CB_Imprimir_Comandas)
        MainWindow.setTabOrder(self.CB_Imprimir_Comandas, self.PB_Imprimir)
        MainWindow.setTabOrder(self.PB_Imprimir, self.PB_ultimo_cliente)
        MainWindow.setTabOrder(self.PB_ultimo_cliente, self.PB_Limpiar)
        MainWindow.setTabOrder(self.PB_Limpiar, self.PB_buscar)
        MainWindow.setTabOrder(self.PB_buscar, self.PB_Nuevo)
        MainWindow.setTabOrder(self.PB_Nuevo, self.PB_Nuevo_2)
        MainWindow.setTabOrder(self.PB_Nuevo_2, self.PB_Nuevo_3)
        MainWindow.setTabOrder(self.PB_Nuevo_3, self.PB_Nuevo_4)
        MainWindow.setTabOrder(self.PB_Nuevo_4, self.PB_Nuevo_5)
        MainWindow.setTabOrder(self.PB_Nuevo_5, self.PB_Nuevo_6)
        MainWindow.setTabOrder(self.PB_Nuevo_6, self.PB_Nuevo_7)
        MainWindow.setTabOrder(self.PB_Nuevo_7, self.PB_Nuevo_8)
        MainWindow.setTabOrder(self.PB_Nuevo_8, self.PB_Nuevo_9)
        MainWindow.setTabOrder(self.PB_Nuevo_9, self.PB_Nuevo_10)
        MainWindow.setTabOrder(self.PB_Nuevo_10, self.PB_Item)
        MainWindow.setTabOrder(self.PB_Item, self.PB_Item_2)
        MainWindow.setTabOrder(self.PB_Item_2, self.PB_Item_3)
        MainWindow.setTabOrder(self.PB_Item_3, self.PB_Item_4)
        MainWindow.setTabOrder(self.PB_Item_4, self.PB_Item_5)
        MainWindow.setTabOrder(self.PB_Item_5, self.PB_Item_6)
        MainWindow.setTabOrder(self.PB_Item_6, self.PB_Item_7)
        MainWindow.setTabOrder(self.PB_Item_7, self.PB_Item_8)
        MainWindow.setTabOrder(self.PB_Item_8, self.PB_Item_9)
        MainWindow.setTabOrder(self.PB_Item_9, self.PB_Item_10)
        MainWindow.setTabOrder(self.PB_Item_10, self.PB_Item_11)
        MainWindow.setTabOrder(self.PB_Item_11, self.PB_Item_12)
        MainWindow.setTabOrder(self.PB_Item_12, self.PB_Item_13)
        MainWindow.setTabOrder(self.PB_Item_13, self.PB_Item_14)
        MainWindow.setTabOrder(self.PB_Item_14, self.PB_Adc_2)
        MainWindow.setTabOrder(self.PB_Adc_2, self.PB_Adc_3)
        MainWindow.setTabOrder(self.PB_Adc_3, self.PB_Adc_4)
        MainWindow.setTabOrder(self.PB_Adc_4, self.PB_Adc_5)
        MainWindow.setTabOrder(self.PB_Adc_5, self.PB_Adc_6)
        MainWindow.setTabOrder(self.PB_Adc_6, self.PB_Adc_7)
        MainWindow.setTabOrder(self.PB_Adc_7, self.listWidget_ticket)
        MainWindow.setTabOrder(self.listWidget_ticket, self.PB_Adc_8)
        MainWindow.setTabOrder(self.PB_Adc_8, self.PB_Adc_9)
        MainWindow.setTabOrder(self.PB_Adc_9, self.PB_Adc_10)
        MainWindow.setTabOrder(self.PB_Adc_10, self.PB_Adc_11)
        MainWindow.setTabOrder(self.PB_Adc_11, self.PB_Adc_12)
        MainWindow.setTabOrder(self.PB_Adc_12, self.PB_Adc_13)
        MainWindow.setTabOrder(self.PB_Adc_13, self.PB_Adc_14)
        MainWindow.setTabOrder(self.PB_Adc_14, self.PB_Adc_15)
        MainWindow.setTabOrder(self.PB_Adc_15, self.PB_Adc_16)
        MainWindow.setTabOrder(self.PB_Adc_16, self.PB_Adc_17)
        MainWindow.setTabOrder(self.PB_Adc_17, self.PB_Adc_18)
        MainWindow.setTabOrder(self.PB_Adc_18, self.PB_Adc_19)
        MainWindow.setTabOrder(self.PB_Adc_19, self.PB_Adc_20)
        MainWindow.setTabOrder(self.PB_Adc_20, self.PB_Adc_21)
        MainWindow.setTabOrder(self.PB_Adc_21, self.cb_ingredientes)
        MainWindow.setTabOrder(self.cb_ingredientes, self.cb_ingredientes_2)
        MainWindow.setTabOrder(self.cb_ingredientes_2, self.cb_ingredientes_3)
        MainWindow.setTabOrder(self.cb_ingredientes_3, self.cb_ingredientes_4)
        MainWindow.setTabOrder(self.cb_ingredientes_4, self.cb_ingredientes_5)
        MainWindow.setTabOrder(self.cb_ingredientes_5, self.cb_ingredientes_6)
        MainWindow.setTabOrder(self.cb_ingredientes_6, self.cb_ingredientes_7)
        MainWindow.setTabOrder(self.cb_ingredientes_7, self.cb_ingredientes_8)
        MainWindow.setTabOrder(self.cb_ingredientes_8, self.cb_ingredientes_9)
        MainWindow.setTabOrder(self.cb_ingredientes_9, self.cb_ingredientes_10)
        MainWindow.setTabOrder(self.cb_ingredientes_10, self.cb_ingredientes_11)
        MainWindow.setTabOrder(self.cb_ingredientes_11, self.cb_ingredientes_12)
        MainWindow.setTabOrder(self.cb_ingredientes_12, self.listWidget_comanda)
        MainWindow.setTabOrder(self.listWidget_comanda, self.PB_Adc)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Nombre", None))
        self.label_5.setText(_translate("MainWindow", "Telefono", None))
        self.label_6.setText(_translate("MainWindow", "Direccion", None))
        self.label_7.setText(_translate("MainWindow", "Coment.", None))
        self.PB_Imprimir.setText(_translate("MainWindow", "F2 - Imprimir", None))
        self.label_9.setText(_translate("MainWindow", "Cod Uber", None))
        self.PB_Limpiar.setText(_translate("MainWindow", "F4 - Limpiar ", None))
        self.CB_Imprimir_Comandas.setText(_translate("MainWindow", "Imprimir comandas", None))
        self.PB_buscar.setText(_translate("MainWindow", "F10 - Buscar", None))
        self.PB_ultimo_cliente.setText(_translate("MainWindow", "F8 - Ult. Cliente", None))
        self.CB_Descuento.setText(_translate("MainWindow", "Descuento", None))
        self.label_8.setText(_translate("MainWindow", "Efectivo", None))
        self.CB_Promo.setText(_translate("MainWindow", "Promo", None))
        self.PB_Nuevo.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Nuevo_2.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Nuevo_3.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Nuevo_4.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Nuevo_5.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Nuevo_6.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Nuevo_7.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Nuevo_8.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Nuevo_9.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Nuevo_10.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_2.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_3.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_4.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_5.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_6.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_7.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_8.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_9.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_10.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_11.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_12.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_13.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Item_14.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_2.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_3.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_4.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_5.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_6.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_7.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_8.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_9.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_10.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_11.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_12.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_13.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_14.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_15.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_16.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_17.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_18.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_19.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_20.setText(_translate("MainWindow", "PushButton", None))
        self.PB_Adc_21.setText(_translate("MainWindow", "PushButton", None))
        self.cb_ingredientes.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_2.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_3.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_4.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_5.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_6.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_7.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_8.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_9.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_10.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_11.setText(_translate("MainWindow", "CheckBox", None))
        self.cb_ingredientes_12.setText(_translate("MainWindow", "CheckBox", None))
        self.label_2.setText(_translate("MainWindow", "Total", None))
        self.label_3.setText(_translate("MainWindow", "Bowls", None))
        self.label_4.setText(_translate("MainWindow", "Bebidas", None))
        self.label_10.setText(_translate("MainWindow", "Postres", None))
        self.TE_Total.setText(_translate("MainWindow", "TextLabel", None))
        self.lb_forma_de_pago.setText(_translate("MainWindow", "FORMA DE PAGO", None))
        self.lb_forma_de_entrega.setText(_translate("MainWindow", "ENTREGA", None))
        self.TE_Bowls.setText(_translate("MainWindow", "0", None))
        self.TE_Bebidas.setText(_translate("MainWindow", "0", None))
        self.TE_Postres.setText(_translate("MainWindow", "0", None))
        self.menuCAJA.setTitle(_translate("MainWindow", "CAJA", None))
        self.actionAbrir_Forumulario.setText(_translate("MainWindow", "Abrir Forumulario", None))

